name: Reopen closed issues
on:
  issues:
    types: [ closed ] 
jobs:
  maybe_reopen_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto Issue Bot
        uses: autoissue/autoissuebot@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

